theme: just-the-docs
title: sc2MeNetDrug
url: "https://fuhaililab.github.io/sc2MeNetDrug"
search:
  heading_level: 3
aux_links:
  "View sc2MeNetDrug on Github":
    - "https://github.com/fuhaililab/sc2MeNetDrug"
aux_links_new_tab: true
markdown: kramdown
color_scheme: green
logo: "pic/sc2MeNetDrug_blue.png"
ga_tracking: G-W3VSLFBJ1M
ga_tracking_anonymize_ip: true
