remote_theme: pmarsceill/just-the-docs
title: sc2MeNetDrug
search:
  heading_level: 3
aux_links:
  "View sc2MeNetDrug on Github":
    - "https://github.com/fuhaililab/sc2MeNetDrug"
aux_links_new_tab: true
markdown: kramdown
color_scheme: green
