
#row base quality control(one column represent one sample)
qualityControl<-function(data,gene_list,group_list=NULL,type_list=NULL){
  data_dim<-dim(data)
  num_sample<-data_dim[2]
  num_gene<-data_dim[1]
  keep_cell_index<-c(1:num_sample)
  keep_gene_index<-c(1:num_gene)
  #remove samples have genes that at least have one count less than 1.2% of total gene
  gene_threshold<-round(num_gene*0.012)
  active_gene<-apply(data>0,2,sum)
  keep_sample_index<-active_gene>=gene_threshold
  data<-data[,keep_sample_index]
  keep_cell_index<-keep_cell_index[keep_sample_index]
  if(!is.null(group_list)){
    group_list<-group_list[keep_sample_index]
  }
  if(!is.null(type_list)){
    type_list=type_list[keep_sample_index]
  }
  #remove samples have not enough counts:1.2% of total gene number
  counts_threshold<-round(0.012*num_gene)
  counts<-apply(data,2,sum)
  keep_sample_index<-counts>=counts_threshold
  data<-data[,keep_sample_index]
  keep_cell_index<-keep_cell_index[keep_sample_index]
  if(!is.null(group_list)){
    group_list<-group_list[keep_sample_index]
  }
  if(!is.null(type_list)){
    type_list=type_list[keep_sample_index]
  }
  
  #remove samples that have high ratio on mitochondrial encoded genes
  mt_gene<-c("MT-ND1","MT-ND2","MT-ND3","MT-ND4L","MT-ND4","MT-ND5","MT-ND6","MT-CYB","MT-CO1","MT-CO2","MT-CO3",
             "MT-ATP6","MT-ATP8","MT-RNR2","MT-RNR1","MT-TA","MT-TR","MT-TN","MT-TD","MT-TC","MT-TE","MT-TQ","MT-TG",
             "MT-TH","MT-TI","MT-TL1","MT-TL2","MT-TK","MT-TM","MT-TF","MT-TP","MT-TS1","MT-TS2","MT-TT","MT-TW",
             "MT-TY","MT-TV")
  inter_mt_gene<-intersect(mt_gene,toupper(gene_list))
  mt_gene_index<-which(toupper(gene_list)%in%inter_mt_gene)
  if(length(inter_mt_gene)!=0){
    mt_express_ratio<-apply(data,2,function(x){
      mt_counts<-sum(x[mt_gene_index])
      total_counts<-sum(x)
      ratio<-mt_counts/total_counts
    })
    set.seed(123)
    mt_cluster<-kmeans(mt_express_ratio,2)$cluster
    cluster_summary<-table(mt_cluster)
    high_number_cluster<-which(cluster_summary==max(cluster_summary))
    low_number_cluster<-which(cluster_summary==min(cluster_summary))
    high_cluster_mean_ratio<-mean(mt_express_ratio[mt_cluster==high_number_cluster])
    low_cluster_mean_ratio<-mean(mt_express_ratio[mt_cluster==low_number_cluster])
    
    
    #if two cluster have low ratio, we keep all 
    if(high_cluster_mean_ratio<0.02&&low_cluster_mean_ratio<0.02){
      keep_sample_index<-rep(T,length(mt_cluster))
    }else if(max(cluster_summary)/min(cluster_summary)>5&&high_cluster_mean_ratio<low_cluster_mean_ratio){
      #if difference between to cluster is remarkable
      #we use soft threshold generated by k-mean
      keep_cluster<-high_number_cluster
      keep_sample_index<-mt_cluster==keep_cluster
    }else{
      #if the difference between to cluster is not remarkable
      #To be safe, we use hard threshold
      mt_threshold<-quantile(mt_express_ratio,c(0.98))[1]
      if(mt_threshold>0.09){
        keep_sample_index<-mt_express_ratio<0.09
      }else{
        keep_sample_index<-mt_express_ratio<mt_threshold
      }
    }
    data<-data[,keep_sample_index]
    keep_cell_index<-keep_cell_index[keep_sample_index]
    if(!is.null(group_list)){
      group_list<-group_list[keep_sample_index]
    }
    if(!is.null(type_list)){
      type_list=type_list[keep_sample_index]
    }
    
    #remove mitochondrial encoded genes
    data<-data[!gene_list%in%mt_gene,]
    keep_gene_index<-keep_gene_index[!gene_list%in%mt_gene]
    gene_list<-rownames(data)
  }
  
  if(is.null(type_list)){
    if(is.null(group_list)){
      return(list(data,gene_list,keep_cell_index,keep_gene_index))
    }else{
      return(list(data,gene_list,group_list,keep_cell_index,keep_gene_index))
    }
  }else{
    if(is.null(group_list)){
      return(list(data,gene_list,type_list,keep_cell_index,keep_gene_index))
    }else{
      return(list(data,gene_list,type_list,group_list,keep_cell_index,keep_gene_index))
    }
  }
  
}

normalization_v2<-function(seurat_data){
  # counts<-apply(data,1,sum)
  # normal_data<-data/counts
  # normal_data<-normal_data*10000
  # normal_data[normal_data<1]=1
  # normal_data<-log(normal_data)
  seurat_data<-NormalizeData(seurat_data)
  seurat_data
}


imputation<-function(seurat_data){
  seurat_data<-RunALRA(seurat_data)
  seurat_data
}

mouse_to_human_convert<-function(data,gene_list){
  load("data/mouse_human_gene_pair.RData")
  gene_list<-data.frame(original_gene=gene_list)
  map_gene_result<-gene_list%>%inner_join(mouse_human_pair,by=c("original_gene"="mouse_gene"))
  data<-data[map_gene_result$original_gene,]
  rownames(data)<-as.character(map_gene_result$human_gene)
  if(sum(duplicated(rownames(data)))>0){
    gene_variance<-apply(data,1,var)
    data<-data[order(gene_variance,decreasing = T),]
    data<-data[!duplicated(rownames(data)),]
  }
  data
}

